package handlers

import (
	"fmt"
	"log"
	"net/http"
	"strings"
	"time"

	"todo-app/db"
	"todo-app/models"
	"todo-app/services"

	"github.com/gin-gonic/gin"
	"github.com/gocql/gocql"
)

var aiClient *services.OpenRouterClient

func InitAIClient() {
	aiClient = services.NewOpenRouterClient()
}

// GenerateTask uses OpenRouter to generate a todo from a prompt
func GenerateTask(c *gin.Context) {
	var req models.GenerateTaskRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	title, description, priority, err := aiClient.GenerateTask(req.Prompt)
	if err != nil {
		log.Printf("AI generation failed: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to generate task: " + err.Error()})
		return
	}

	// Create the todo in DB
	id, _ := gocql.RandomUUID()
	now := time.Now()

	err = db.Session.Query(`
		INSERT INTO todos (id, title, description, is_completed, priority, status, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`, id, title, description, false, priority, "todo", now, now).Exec()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save generated task"})
		return
	}

	todo := models.Todo{
		ID:          id,
		Title:       title,
		Description: description,
		IsCompleted: false,
		Priority:    models.Priority(priority),
		Status:      "todo",
		CreatedAt:   now,
		UpdatedAt:   now,
	}

	services.LogHistory(id, "ai_generated", "Generated by AI", map[string]string{
		"prompt_used": req.Prompt,
		"model":       "gpt-oss-20b",
	})

	c.JSON(http.StatusCreated, gin.H{
		"todo":    todo,
		"message": "Task generated by AI",
	})
}

// EmbedTodo generates an embedding for a todo and stores it
func EmbedTodo(c *gin.Context) {
	idStr := c.Param("id")
	todoID, err := gocql.ParseUUID(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})
		return
	}

	// Get the todo
	var title, description string
	err = db.Session.Query(`SELECT title, description FROM todos WHERE id = ?`, todoID).Scan(&title, &description)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Todo not found"})
		return
	}

	// Generate embedding from title + description
	textToEmbed := title
	if description != "" {
		textToEmbed = title + ". " + description
	}

	embedding, err := aiClient.GenerateEmbedding(textToEmbed)
	if err != nil {
		log.Printf("Embedding generation failed: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to generate embedding: " + err.Error()})
		return
	}

	// Store embedding in Cassandra
	embID, _ := gocql.RandomUUID()
	now := time.Now()

	// Build the vector string for CQL
	vectorStr := formatVectorForCQL(embedding)

	err = db.Session.Query(
		fmt.Sprintf(`INSERT INTO todo_embeddings (id, todo_id, title, embedding, created_at) VALUES (?, ?, ?, %s, ?)`, vectorStr),
		embID, todoID, title, now,
	).Exec()

	if err != nil {
		log.Printf("Failed to store embedding: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to store embedding: " + err.Error()})
		return
	}

	services.LogHistory(todoID, "embedding_created", "Vector embedding generated", map[string]string{
		"dimensions": fmt.Sprintf("%d", len(embedding)),
	})

	// Return first 20 dimensions as preview
	preview := embedding
	if len(preview) > 20 {
		preview = preview[:20]
	}

	c.JSON(http.StatusOK, gin.H{
		"todo_id":            todoID.String(),
		"embedding_dimensions": len(embedding),
		"embedding_preview":  preview,
		"message":            "Embedding generated and stored",
	})
}

// EmbedAllTodos generates embeddings for all todos that don't have one yet
func EmbedAllTodos(c *gin.Context) {
	// Step 1: Collect all todos first (close iterator before making other queries)
	type todoItem struct {
		ID          gocql.UUID
		Title       string
		Description string
	}
	var todos []todoItem

	iter := db.Session.Query(`SELECT id, title, description FROM todos`).Iter()
	var todoID gocql.UUID
	var title, description string
	for iter.Scan(&todoID, &title, &description) {
		todos = append(todos, todoItem{ID: todoID, Title: title, Description: description})
	}
	if err := iter.Close(); err != nil {
		log.Printf("Error closing todos iterator: %v", err)
	}

	log.Printf("📋 Found %d todos to process", len(todos))

	// Step 2: Process each todo
	var embedded int
	for _, todo := range todos {
		// Check if embedding already exists
		var count int
		db.Session.Query(`SELECT COUNT(*) FROM todo_embeddings WHERE todo_id = ? ALLOW FILTERING`, todo.ID).Scan(&count)
		if count > 0 {
			log.Printf("⏭️ Skipping %s (already embedded)", todo.Title)
			continue
		}

		textToEmbed := todo.Title
		if todo.Description != "" {
			textToEmbed = todo.Title + ". " + todo.Description
		}

		embedding, err := aiClient.GenerateEmbedding(textToEmbed)
		if err != nil {
			log.Printf("❌ Failed to embed todo %s: %v", todo.ID.String(), err)
			continue
		}

		embID, _ := gocql.RandomUUID()
		now := time.Now()
		vectorStr := formatVectorForCQL(embedding)

		err = db.Session.Query(
			fmt.Sprintf(`INSERT INTO todo_embeddings (id, todo_id, title, embedding, created_at) VALUES (?, ?, ?, %s, ?)`, vectorStr),
			embID, todo.ID, todo.Title, now,
		).Exec()

		if err != nil {
			log.Printf("❌ Failed to store embedding for %s: %v", todo.ID.String(), err)
			continue
		}
		log.Printf("✅ Embedded: %s", todo.Title)
		embedded++
	}

	c.JSON(http.StatusOK, gin.H{
		"message":  fmt.Sprintf("Embedded %d todos", embedded),
		"embedded": embedded,
	})
}

// VectorSearch performs ANN vector search on Cassandra
func VectorSearch(c *gin.Context) {
	var req models.VectorSearchRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	if req.TopK <= 0 {
		req.TopK = 5
	}

	// Generate embedding for search query
	queryEmbedding, err := aiClient.GenerateEmbedding(req.Query)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to generate query embedding: " + err.Error()})
		return
	}

	// Perform ANN search in Cassandra
	vectorStr := formatVectorForCQL(queryEmbedding)
	query := fmt.Sprintf(
		`SELECT id, todo_id, title, similarity_cosine(embedding, %s) as score FROM todo_embeddings ORDER BY embedding ANN OF %s LIMIT ?`,
		vectorStr, vectorStr,
	)

	iter := db.Session.Query(query, req.TopK).Iter()
	var results []models.SearchResult
	var embID, todoID gocql.UUID
	var embTitle string
	var score float32

	for iter.Scan(&embID, &todoID, &embTitle, &score) {
		// Get full todo details
		var todo models.Todo
		err := db.Session.Query(`SELECT id, title, description, is_completed, priority, status, created_at, updated_at FROM todos WHERE id = ?`, todoID).
			Scan(&todo.ID, &todo.Title, &todo.Description, &todo.IsCompleted, &todo.Priority, &todo.Status, &todo.CreatedAt, &todo.UpdatedAt)
		if err != nil {
			continue
		}

		results = append(results, models.SearchResult{
			Todo:   todo,
			Score:  score,
			Method: "vector",
		})
	}
	iter.Close()

	if results == nil {
		results = []models.SearchResult{}
	}

	// Query embedding preview (first 20 dims)
	queryPreview := queryEmbedding
	if len(queryPreview) > 20 {
		queryPreview = queryPreview[:20]
	}

	c.JSON(http.StatusOK, gin.H{
		"query":                req.Query,
		"results":              results,
		"query_embedding_preview": queryPreview,
		"total_dimensions":     len(queryEmbedding),
	})
}

// CompareSearch runs both text search and vector search side by side
func CompareSearch(c *gin.Context) {
	query := c.Query("q")
	if query == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Search query is required"})
		return
	}

	// 1. Normal text search
	var normalResults []models.SearchResult
	queryLower := strings.ToLower(query)

	iter := db.Session.Query(`SELECT id, title, description, is_completed, priority, status, created_at, updated_at FROM todos`).Iter()
	var todo models.Todo
	for iter.Scan(&todo.ID, &todo.Title, &todo.Description, &todo.IsCompleted, &todo.Priority, &todo.Status, &todo.CreatedAt, &todo.UpdatedAt) {
		if strings.Contains(strings.ToLower(todo.Title), queryLower) ||
			strings.Contains(strings.ToLower(todo.Description), queryLower) {
			normalResults = append(normalResults, models.SearchResult{
				Todo:   todo,
				Method: "text",
			})
		}
	}
	iter.Close()

	// 2. Vector search
	var vectorResults []models.SearchResult
	var queryPreview []float32

	queryEmbedding, err := aiClient.GenerateEmbedding(query)
	if err == nil {
		queryPreview = queryEmbedding
		if len(queryPreview) > 20 {
			queryPreview = queryPreview[:20]
		}

		vectorStr := formatVectorForCQL(queryEmbedding)
		annQuery := fmt.Sprintf(
			`SELECT id, todo_id, title, similarity_cosine(embedding, %s) as score FROM todo_embeddings ORDER BY embedding ANN OF %s LIMIT 5`,
			vectorStr, vectorStr,
		)

		annIter := db.Session.Query(annQuery).Iter()
		var embID, todoID gocql.UUID
		var embTitle string
		var score float32

		for annIter.Scan(&embID, &todoID, &embTitle, &score) {
			var vTodo models.Todo
			err := db.Session.Query(`SELECT id, title, description, is_completed, priority, status, created_at, updated_at FROM todos WHERE id = ?`, todoID).
				Scan(&vTodo.ID, &vTodo.Title, &vTodo.Description, &vTodo.IsCompleted, &vTodo.Priority, &vTodo.Status, &vTodo.CreatedAt, &vTodo.UpdatedAt)
			if err != nil {
				continue
			}

			// Get embedding preview for this result
			var resultEmbedding []float32
			db.Session.Query(`SELECT embedding FROM todo_embeddings WHERE id = ?`, embID).Scan(&resultEmbedding)
			preview := resultEmbedding
			if len(preview) > 10 {
				preview = preview[:10]
			}

			vectorResults = append(vectorResults, models.SearchResult{
				Todo:             vTodo,
				Score:            score,
				Method:           "vector",
				EmbeddingPreview: preview,
			})
		}
		annIter.Close()
	}

	if normalResults == nil {
		normalResults = []models.SearchResult{}
	}
	if vectorResults == nil {
		vectorResults = []models.SearchResult{}
	}

	c.JSON(http.StatusOK, models.CompareSearchResponse{
		Query:          query,
		NormalResults:  normalResults,
		VectorResults:  vectorResults,
		QueryEmbedding: queryPreview,
	})
}

// formatVectorForCQL converts a float32 slice to CQL vector literal
func formatVectorForCQL(v []float32) string {
	parts := make([]string, len(v))
	for i, val := range v {
		parts[i] = fmt.Sprintf("%f", val)
	}
	return "[" + strings.Join(parts, ",") + "]"
}
