{
 "title": "Cassandra Cluster (JMX Exporter)",
 "description": "Cassandra Monitoring (JMX Exporter)",
 "tags": [ "cassandra" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"cassandra\"}, cluster)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(up{job=\"cassandra\",cluster=\"$cluster\"}, datacenter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_failuredetector_upendpointcount{cluster=~\"$cluster\",datacenter=~\"$datacenter\"})"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_failuredetector_downendpointcount{cluster=~\"$cluster\",datacenter=~\"$datacenter\"})"
    }
   ]
  },
  {
   "title": "Native Clients Connected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_client_connectednativeclients_value{cluster=~\"$cluster\",datacenter=~\"$datacenter\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 0 },
   "options": {
    "content": "<img src=\"https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg\" width=\"150\" height=\"100\" style=\"background-color:white;\"/>\n<span style=\"font-family:verdana,geneva,sans-serif;\"><span style=\"font-size:28px;\"><span style=\"color:#ffffff;\">&nbsp;&nbsp;Cassandra Cluster</span></span></span>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 }, "options": { "content": "# Cluster Operations" } },
  {
   "title": "Cluster Ops",
   "type": "timeseries",
   "description": "Total aggregated requests per second cluster-wise",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"CASRead\"})",
     "legendFormat": "CasRead"
    },
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"CASWrite\"})",
     "legendFormat": "CasWrite"
    },
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"RangeSlice\"})",
     "legendFormat": "RangeSlice"
    },
    {
     "expr": "sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"ViewWrite\"})",
     "legendFormat": "ViewWrite"
    }
   ]
  },
  {
   "title": "Operations per Instance",
   "type": "timeseries",
   "description": "Requests served by each instance of the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (instance), \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 }, "options": { "content": "# Reads and Writes" } },
  {
   "title": "Read Operations",
   "type": "timeseries",
   "description": "Read operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Write Operations",
   "type": "timeseries",
   "description": "Write operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "options": { "content": "# Latencies" } },
  {
   "title": "Average Read Latency per Instance",
   "type": "timeseries",
   "description": "Average read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_mean{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "75th Percentile Read Latency per Instance",
   "type": "timeseries",
   "description": "75th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_75thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "99th Percentile Read Latency per Instance",
   "type": "timeseries",
   "description": "99th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_99thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Average Write Latency per Instance",
   "type": "timeseries",
   "description": "Average write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_mean{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "75th Percentile Write Latency per Instance",
   "type": "timeseries",
   "description": "75th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_75thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "99th Percentile Write Latency per Instance",
   "type": "timeseries",
   "description": "99th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_clientrequest_latency_99thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "options": { "content": "# Timeouts and Unavailables" } },
  {
   "title": "Timeouts per Instance Rate",
   "type": "timeseries",
   "description": "Timeouts for read and write for each instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_clientrequest_timeouts_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (instance), \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_All"
    },
    {
     "expr": "label_replace(cassandra_clientrequest_timeouts_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_R"
    },
    {
     "expr": "label_replace(cassandra_clientrequest_timeouts_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_W"
    }
   ]
  },
  {
   "title": "Unavailables per Instance Rate",
   "type": "timeseries",
   "description": "Unavailables operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_clientrequest_unavailables_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (instance), \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_All"
    },
    {
     "expr": "label_replace(cassandra_clientrequest_unavailables_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Read\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_R"
    },
    {
     "expr": "label_replace(cassandra_clientrequest_unavailables_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\",scope=\"Write\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_W"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 }, "options": { "content": "# Errors" } },
  {
   "title": "Exceptions per Instance",
   "type": "timeseries",
   "description": "Exceptions for each instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_storage_exceptions_count{cluster=\"$cluster\",datacenter=~\"$datacenter\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Total Connection Timeouts",
   "type": "timeseries",
   "description": "Total connection timeouts in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cassandra_connection_totaltimeouts_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\"})",
     "legendFormat": "Connection Timeouts"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 }, "options": { "content": "# Thread Pools" } },
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "description": "Active tasks per thread type",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_activetasks{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (threadpools)",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "description": "Pending tasks per thread type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (threadpools)",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "timeseries",
   "description": "Blocked tasks per thread type",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_currentlyblockedtasks_count{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (threadpools)",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Dropped Messages Rates",
   "type": "timeseries",
   "description": "Dropped messages rates by message type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cassandra_droppedmessage_dropped_oneminuterate{cluster=\"$cluster\",datacenter=~\"$datacenter\"}) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 }, "options": { "content": "# Compactions and SSTables" } },
  {
   "title": "Pending and Running Compactions",
   "type": "timeseries",
   "description": "Pending and Running compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_compaction_pendingtasks_value{cluster=\"$cluster\",datacenter=~\"$datacenter\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_Pending"
    },
    {
     "expr": "label_replace(cassandra_threadpools_activetasks{cluster=\"$cluster\",datacenter=~\"$datacenter\",threadpools=\"CompactionExecutor\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_Active"
    }
   ]
  },
  {
   "title": "Completed Compactions",
   "type": "timeseries",
   "description": "Completed compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_compaction_completedtasks_value{cluster=\"$cluster\",datacenter=~\"$datacenter\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Bytes Compacted",
   "type": "timeseries",
   "description": "Bytes compacted per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_compaction_bytescompacted_count{cluster=\"$cluster\",datacenter=~\"$datacenter\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Live SSTables per Instance",
   "type": "timeseries",
   "description": "Live SSTables per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_table_livesstablecount_value{cluster=\"$cluster\",datacenter=~\"$datacenter\"}, \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "SSTables per Read Histogram",
   "type": "timeseries",
   "description": "SSTables per read histogram percentiles",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cassandra_table_sstablesperreadhistogram_50thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "avg(cassandra_table_sstablesperreadhistogram_75thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\"})",
     "legendFormat": "p75"
    },
    {
     "expr": "avg(cassandra_table_sstablesperreadhistogram_99thpercentile{cluster=\"$cluster\",datacenter=~\"$datacenter\"})",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}